version: '2'
services:
    porka_light_stock_data_base-app:
        image: porka_light_stock_data_base
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://porka_light_stock_data_base-mysql:3306/porka_light_stock_data_base?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    porka_light_stock_data_base-mysql:
        extends:
            file: mysql.yml
            service: porka_light_stock_data_base-mysql
